name = "thestacc-2026-site"
main = "worker.js"
account_id = "2436fd46542e5271272596fe5ae5fc98"
compatibility_date = "2025-07-01"

[assets]
directory = "dist"
html_handling = "force-trailing-slash"
not_found_handling = "404-page"
